- job:
    name: erase_all_environments
    parameters:
      - node:
          name: SLAVE_NAMES
          default-slaves:
            - Slave-srv129
            - Slave-srv130
            - Slave-srv131
            - Slave-srv132
            - Slave-srv133
            - Slave-srv134
            - Slave-srv135
            - Slave-srv136
          allowed-slaves:
            - Slave-srv129
            - Slave-srv130
            - Slave-srv131
            - Slave-srv132
            - Slave-srv133
            - Slave-srv134
            - Slave-srv135
            - Slave-srv136
          ignore-offline-nodes: true
          allowed-multiselect: true
    builders:
        - shell: |
            set +e
            dos.py list > temp
            while read -r line
            do
            set -e
            dos.py erase $line || true
            done < temp
    project-type: freestyle
    defaults: global
    description: 'Erase all environments on node'
    disabled: false
    display-name: 'Erase all environments on node'
    concurrent: true
    retry-count: 3
    logrotate:
      daysToKeep: 1
      numToKeep: 5
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
    publishers:
      - email:
          recipients: efazliev@mirantis.com