- job:
    parameters:
      - string:
          name: ISO_DIR
          default: "/var/www/fuelweb-iso"
      - string:
          name: SNAPSHOT_NAME
      - string:
          name: ERASE_PREV_ENV
          default: "FALSE"
      - string:
          name: SEGMENT_TYPE
      - string:
          name: DVR_ENABLE
          default: "FALSE"
      - string:
          name: L3_HA_ENABLE
          default: "FALSE"
      - string:
          name: L2_POP_ENABLE
          default: "FALSE"
      - string:
          name: CEPH_ENABLE
          default: "FALSE"
      - string:
          name: RADOS_ENABLE
          default: "FALSE"
      - string:
          name: SAHARA_ENABLE
          default: "FALSE"
      - string:
          name: MURANO_ENABLE
          default: "FALSE"
      - string:
          name: MONGO_ENABLE
          default: "FALSE"
      - string:
          name: CEILOMETER_ENABLE
          default: "FALSE"
      - string:
          name: DISABLE_SSL
          default: "TRUE"
      - string:
          name: FUEL_DEV_VER
          default: "2.9.16"
      - string:
          name: FUEL_QA_VER
          default: "master"
      - string:
          name: SLAVE_COMPUTE_NODE_MEMORY
      - string:
          name: COMPUTES_COUNT
          default: "2"
      - string:
          name: CONTROLLERS_COUNT
          default: "3"
      - string:
          name: IRONICS_COUNT
          default: "0"
      - string:
          name: NOVA_QUOTAS_ENABLED
          default: "FALSE"
      - string:
          name: SLAVE_NODE_CPU
          default: "1"
      - string:
          name: SLAVE_NODE_MEMORY
          default: "4096"
      - string:
          name: DEPLOYMENT_TIMEOUT
          default: "10000"
      - string:
          name: MOS_VERSION
      - string:
          name: INTERFACE_MODEL
          default: "virtio"
      - string:
          name: KVM_USE
          default: "TRUE"

    name: OK_9.0_create_param_environment

    builders:
        - shell: |
            set +x
            echo `hostname`
            ISO_NAME=`ls "$ISO_DIR"`
            ENV_NAME=MOS_CI_"$ISO_NAME"

            if [ "$MOS_VERSION" == 'mitaka' ] || [ "$MOS_VERSION" == 'kilo' ] ;
            then
            ISO_ID=`echo "$ISO_NAME" | cut -f4 -d-`
            else
            ISO_ID=`echo "$ISO_NAME" | cut -f3 -d-`
            fi

            virtualenv venv
            . venv/bin/activate

            export ISO_PATH="$ISO_DIR"/"$ISO_NAME"
            export ENV_NAME="$ENV_NAME"
            export ERASE_PREV_ENV="$ERASE_PREV_ENV"
            export SEGMENT_TYPE="$SEGMENT_TYPE"
            export DVR_ENABLE="$DVR_ENABLE"
            export L3_HA_ENABLE="$L3_HA_ENABLE"
            export L2_POP_ENABLE="$L2_POP_ENABLE"
            export CEPH_ENABLE="$CEPH_ENABLE"
            export RADOS_ENABLE="$RADOS_ENABLE"
            export SAHARA_ENABLE="$SAHARA_ENABLE"
            export MURANO_ENABLE="$MURANO_ENABLE"
            export MONGO_ENABLE="$MONGO_ENABLE"
            export CEILOMETER_ENABLE="$CEILOMETER_ENABLE"
            export IRONIC_ENABLE="$IRONIC_ENABLE"
            export DISABLE_SSL="$DISABLE_SSL"
            export FUEL_DEV_VER="$FUEL_DEV_VER"
            export COMPUTES_COUNT="$COMPUTES_COUNT"
            export CONTROLLERS_COUNT="$CONTROLLERS_COUNT"
            export IRONICS_COUNT="$IRONICS_COUNT"
            export FUEL_QA_VER="$FUEL_QA_VER"
            export NOVA_QUOTAS_ENABLED="$NOVA_QUOTAS_ENABLED"
            export SLAVE_NODE_CPU="$SLAVE_NODE_CPU"
            export SLAVE_NODE_MEMORY="$SLAVE_NODE_MEMORY"
            export DEPLOYMENT_TIMEOUT="$DEPLOYMENT_TIMEOUT"
            export INTERFACE_MODEL="$INTERFACE_MODEL"
            export KVM_USE="$KVM_USE"

            /bin/bash -x deploy_env.sh
            fi

    project-type: freestyle
    defaults: global
    node: Slave-srv150
    scm:
       - 9.0-mos-ci-deployment-scripts-gd
    description: 'Create environment with parameters, specified by PARAM string.'
    disabled: false
    display-name: 'Personal_OK_Create Parameterized Environment with 9.0 stable'
    concurrent: true
    browser: githubweb
    retry-count: 3
    logrotate:
      daysToKeep: 20
      numToKeep: 200
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
    publishers:
      - workspace-cleanup:
          fail-build: false
      - email:
          recipients: efazliev@mirantis.com
