- job:
    name: 8.0_create_param_environment_common_maintenance
    wrappers:
      - build-name:
          name: ${BUILD_NUMBER}.${FILE,path="build-name-setter.info"}
      - ansicolor
    parameters:
      - string:
          name: MAGNET_LINK
          default: 'magnet:?xt=urn:btih:4709616bca3e570a951c30b7cf9ffeb2c0359f5c&dn=MirantisOpenStack-8.0.iso&tr=http%3A%2F%2Ftracker01-bud.infra.mirantis.net%3A8080%2Fannounce&tr=http%3A%2F%2Ftracker01-scc.infra.mirantis.net%3A8080%2Fannounce&tr=http%3A%2F%2Ftracker01-msk.infra.mirantis.net%3A8080%2Fannounce&ws=http%3A%2F%2Fvault.infra.mirantis.net%2FMirantisOpenStack-8.0.iso'
          description: 'ISO magnet link'
      - string:
          name: ENV_NAME
          default: maintenance_env_8.0
      - string:
          name: UPGRADE_TARBALL_MAGNET_LINK
          default: 'magnet:?xt=urn:btih:2bd0d09d0db86967bf00dbbb3265ac47e224009f&dn=fuel-8.0-upgrade-152-2015-11-12%5F13-42-00.tar.lrz&tr=http%3A%2F%2Ftracker01-bud.infra.mirantis.net%3A8080%2Fannounce&tr=http%3A%2F%2Ftracker01-mnv.infra.mirantis.net%3A8080%2Fannounce&tr=http%3A%2F%2Ftracker01-msk.infra.mirantis.net%3A8080%2Fannounce&ws=http%3A%2F%2Fsrv89-bud.infra.mirantis.net%2Ffuelweb-iso%2Ffuel-8.0-upgrade-152-2015-11-12%5F13-42-00.tar.lrz'
          description: 'Upgrade tarball magnet link'
      - string:
          name: DEB_LATEST
          default: 'latest'
          description: "Snapshot timestamp without version id. E.g.: '2015-09-27-173001' or 'latest'"
      - string:
          name: RPM_LATEST
          default: 'latest'
      - string:
          name: UBUNTU_MIRROR_ID
          default: 'latest'
      - bool:
          name: ENABLE_PROPOSED
          default: false
      - bool:
          name: ENABLE_SECURITY
          default: true
      - bool:
          name: ENABLE_UPDATES
          default: true
      - string:
          name: SNAPSHOT_NAME
      - string:
          name: TEST_TYPE
      - string:
          name: ERASE_PREV_ENV
          default: "FALSE"
      - string:
          name: SEGMENT_TYPE
      - string:
          name: DVR_ENABLE
          default: "FALSE"
      - string:
          name: L3_HA_ENABLE
          default: "FALSE"
      - string:
          name: L2_POP_ENABLE
          default: "FALSE"
      - string:
          name: CEPH_ENABLE
          default: "FALSE"
      - string:
          name: CINDER_ENABLE
          default: "TRUE"
      - string:
          name: LVM_ENABLE
          default: "TRUE"
      - string:
          name: RADOS_ENABLE
          default: "FALSE"
      - string:
          name: SAHARA_ENABLE
          default: "FALSE"
      - string:
          name: MURANO_ENABLE
          default: "FALSE"
      - string:
          name: MONGO_ENABLE
          default: "FALSE"
      - string:
          name: CEILOMETER_ENABLE
          default: "FALSE"
      - string:
          name: DISABLE_SSL
          default: "TRUE"
      - string:
          name: FUEL_QA_VER
          default: "stable/8.0"
      - string:
          name: SLAVE_COMPUTE_NODE_MEMORY
      - string:
          name: COMPUTES_COUNT
          default: "2"
      - string:
          name: CONTROLLERS_COUNT
          default: "3"
      - string:
          name: IRONICS_COUNT
          default: "0"
      - string:
          name: NOVA_QUOTAS_ENABLED
          default: "FALSE"
      - string:
          name: SLAVE_NODE_CPU
          default: "1"
      - string:
          name: SLAVE_NODE_MEMORY
          default: "4096"
      - string:
          name: DEPLOYMENT_TIMEOUT
          default: "10000"
      - string:
          name: MOS_VERSION
      - string:
          name: INTERFACE_MODEL
          default: "virtio"
      - string:
          name: KVM_USE
          default: "FALSE"
      - string:
          name: TEMPEST
          default: "FALSE"
      - string:
          name: REPLICA_CEPH
          default: "FALSE"
      - string:
          name: CEPH_GLANCE_ENABLE
          default: "FALSE"

    builders:
        - shell:
            !include-raw: 'builders/maintenance_deploy_env_8_0_common.sh'

    scm:
       - mos-ci-deployment-scripts
    project-type: freestyle
    node: maintenance
    defaults: global
    description: 'Create environment with parameters, specified by PARAM string.'
    disabled: false
    display-name: '8.0 Create Parameterized Environment common (maintenance)'
    concurrent: true
    browser: githubweb
    retry-count: 3
    logrotate:
      daysToKeep: 14
      numToKeep: 50
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
    publishers:
      - workspace-cleanup:
          fail-build: false
      - email:
          recipients: agromov@mirantis.com
      - archive:
          artifacts: 'mos_tests.yaml'
          allow-empty: 'true'
          fingerprint: true
      - archive:
          artifacts: '3_controllers_2compute_neutron_env.yaml'
          allow-empty: 'true'
          fingerprint: true
